-- place_order has always returned only order_id and total_amount, but
-- PlaceOrderResult (types/models.ts) has always claimed order_number is a
-- guaranteed string. On web, passing that undefined value through
-- router.replace({ params: { orderNumber: result.order_number } }) gets
-- stringified into the URL as the literal text "undefined", which then
-- defeats the `??` fallback on the order-success screen since "undefined"
-- is a non-nullish string — showing the literal word on screen.
--
-- Same body as 044, except the order insert also returns order_number
-- (generated by the existing BEFORE INSERT trigger) and the final result
-- includes it.
CREATE OR REPLACE FUNCTION place_order(
  p_address_id    UUID,
  p_payment_method payment_method DEFAULT 'cash_on_delivery',
  p_notes         TEXT DEFAULT NULL
)
RETURNS JSONB LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_user_id       UUID := auth.uid();
  v_cart_id       UUID;
  v_order_id      UUID;
  v_order_number  TEXT;
  v_total         NUMERIC(10,2) := 0;
  v_address       JSONB;
  v_item          RECORD;
  v_stock_before  INT;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'UNAUTHENTICATED';
  END IF;

  SELECT id INTO v_cart_id FROM carts WHERE user_id = v_user_id;
  IF v_cart_id IS NULL THEN
    RAISE EXCEPTION 'EMPTY_CART';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM cart_items WHERE cart_id = v_cart_id) THEN
    RAISE EXCEPTION 'EMPTY_CART';
  END IF;

  SELECT to_jsonb(a.*) INTO v_address
  FROM addresses a
  WHERE a.id = p_address_id AND a.user_id = v_user_id;

  IF v_address IS NULL THEN
    RAISE EXCEPTION 'INVALID_ADDRESS';
  END IF;

  FOR v_item IN
    SELECT ci.quantity,
           p.id            AS product_id,
           p.name_ar,
           p.name_en,
           COALESCE(p.discount_price, p.price) AS unit_price,
           p.stock_quantity,
           p.min_order_quantity
    FROM cart_items ci
    JOIN products p ON p.id = ci.product_id
    WHERE ci.cart_id = v_cart_id AND p.is_available = TRUE
    FOR UPDATE OF p
  LOOP
    IF v_item.quantity < v_item.min_order_quantity THEN
      RAISE EXCEPTION 'BELOW_MIN_QUANTITY:% (%)', v_item.name_ar, v_item.min_order_quantity;
    END IF;
    IF v_item.stock_quantity < v_item.quantity THEN
      RAISE EXCEPTION 'INSUFFICIENT_STOCK:% (%)', v_item.name_ar, v_item.product_id;
    END IF;
    v_total := v_total + (v_item.unit_price * v_item.quantity);
  END LOOP;

  INSERT INTO orders (user_id, status, total_amount, delivery_address, payment_method, notes)
  VALUES (v_user_id, 'pending', v_total, v_address, p_payment_method, p_notes)
  RETURNING id, order_number INTO v_order_id, v_order_number;

  FOR v_item IN
    SELECT ci.quantity,
           p.id   AS product_id,
           p.name_ar,
           p.name_en,
           COALESCE(p.discount_price, p.price) AS unit_price
    FROM cart_items ci
    JOIN products p ON p.id = ci.product_id
    WHERE ci.cart_id = v_cart_id
  LOOP
    INSERT INTO order_items (order_id, product_id, product_name_ar, product_name_en, unit_price, quantity)
    VALUES (v_order_id, v_item.product_id, v_item.name_ar, v_item.name_en, v_item.unit_price, v_item.quantity);

    UPDATE products
    SET stock_quantity = stock_quantity - v_item.quantity
    WHERE id = v_item.product_id
    RETURNING stock_quantity INTO v_stock_before;

    INSERT INTO inventory_logs (product_id, action, quantity_change, quantity_before, quantity_after, reference_id)
    VALUES (
      v_item.product_id,
      'sale',
      -v_item.quantity,
      v_stock_before + v_item.quantity,
      v_stock_before,
      v_order_id
    );
  END LOOP;

  DELETE FROM cart_items WHERE cart_id = v_cart_id;

  INSERT INTO order_status_history (order_id, status) VALUES (v_order_id, 'pending');

  RETURN jsonb_build_object('order_id', v_order_id, 'order_number', v_order_number, 'total_amount', v_total);
END;
$$;
